SQL movies complete
DmitrijsRuskovs/SQL_training pull request #1
Opened 2021-09-04 12:01 UTC by DmitrijsRuskovs

2021-09-06 17:01 UTC, ausmoons requested changes
![image](https://user-images.githubusercontent.com/53189160/132247259-4b3b0485-98af-40fc-8179-c0fde1bfae58.png)
Neiziet visi testi no 07

2021-09-06 17:01 UTC, ausmoons commented on sql-movies/src/queries/select.ts
> +  SELECT *
Te noteikti prasītos tab.

2021-09-06 17:01 UTC, ausmoons commented on sql-movies/src/queries/select.ts
> +  return `Select Count(*) as c from ${table}`
nav labi lietot tādus saīsināumus kā c. Jābūt saprotamam nosaukumam

2021-09-06 17:01 UTC, ausmoons commented on sql-movies/test/05-insert-relationship-data.test.ts
> +      var currentRow = productionCompanyRows.find(row => row.company_name == productionCompany);
Pāŗskati visus failus, lai tab ir sakārtots

2021-09-07 12:01 UTC, DmitrijsRuskovs commented on sql-movies/src/queries/select.ts
> +  SELECT *
Pielikts

2021-09-07 12:02 UTC, DmitrijsRuskovs commented on sql-movies/src/queries/select.ts
> +  return `Select Count(*) as c from ${table}`
Piekrītu, bet noteikumos no izveidotāja (augstāk aizkomentēts) prasīts nosaukt "as c"

2021-09-07 18:40 UTC, ausmoons approved these changes

2021-09-26 06:09 UTC, merged